[package]
name = "glau-playpen"
version = "1.0.0"
authors = ["William Wallace <me@wiox.me>"]
edition = "2018"
publish = false

[dependencies]
mlua = { git = "https://github.com/ChurchOfMiku/mlua", features = ["glau54"] }
